if (CMAKE_GENERATOR MATCHES "^Ninja" AND (CMAKE_CXX_COMPILER_ID STREQUAL "GNU" OR CMAKE_CXX_COMPILER_ID STREQUAL "Clang"))
   option (NINJA_FORCE_COLORED_OUTPUT "Always produce ANSI-colored output (GNU/Clang only)." ON)
   if (NINJA_FORCE_COLORED_OUTPUT)
      if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
         add_compile_options("-fdiagnostics-color=always")
      elseif (CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
         add_compile_options("-fcolor-diagnostics")
      endif()
   endif()
endif()

set_property(GLOBAL PROPERTY USE_FOLDERS ON)
set(CMAKE_CXX_EXTENSIONS OFF)
